
name: ZIIT API CALL

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  call_api:
    runs-on: ubuntu-latest
    steps:
      - name: Make a GET request
        run: |
          curl -X GET "https://ziit.app/api/external/stats?timeRange=all_time&midnightOffsetSeconds=0" \
            -H "Authorization: Bearer ${{ secrets.ZIIT_API_KEY }}"